name: vivahigienizado
description: "App Viva Higienizado – Turismo Local / Serviços"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Login e sessão
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # API com cookies
  dio: ^5.4.0
  cookie_jar: ^4.0.2
  dio_cookie_manager: ^3.1.0

  # FOTO / VÍDEO
  image_picker: ^1.1.0

  # GPS
  geolocator: ^14.0.2

  # Permissões (câmera, áudio, arquivos, localização)
  permission_handler: ^11.4.0

  # NECESSÁRIO para armazenamento de cookies no Android e Linux
  path_provider: ^2.1.3

  # TOKEN Django armazenado de forma segura (Android, iOS e Linux)
  flutter_secure_storage: ^9.0.0
  flutter_secure_storage_linux: ^1.1.3
  #file_picker: ^6.1.0
  file_picker: ^6.1.7
  video_thumbnail: ^0.5.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

